#about server
server:
  port: 8081

#mapper
spring:
  #jdbc
  datasource:
    url: jdbc:mysql://rm-uf69p0lh6oeeipk15zo.mysql.rds.aliyuncs.com:3306/work?autoReconnect=true&amp;rewriteBatchedStatements=true&amp;socketTimeout=30000&amp;connectTimeout=3000
    username: root
    password: Tt5685669
    driver-class-name: com.mysql.jdbc.Driver

 # 连接池设置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # Oracle请使用select 1 from dual
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true

  #redis
  redis:
    host: 139.196.127.16
    port: 6379
    password: Tt5685669
    database: 1
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500
      min-idle: 0
    timeout: 0

redis:
  nodes: 139.196.127.16:6379
  password: Tt5685669
  pool:
    max-active: 8
    max-wait: -1
    max-idle: 500
    min-idle: 0
  connectionTimeout: 3000
  soTimeout: 3000
  maxAttempts: 5

#mybatis mapper
mybatis:
  mapper-locations: classpath*:mapper/*.xml
